name: CI - Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 🧪CI - Go Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: telemetry_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_DSN: root:root@tcp(127.0.0.1:3306)/telemetry_test?charset=utf8mb4&parseTime=True&loc=Local

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Instalar dependências
        run: go mod tidy

      - name: Rodar testes
        run: go test ./... -v
